apiVersion: v1
kind: Service
metadata:
  name: seyoawe-engine
  namespace: seyoawe
  labels:
    app: seyoawe-engine
    project: seyoawe
spec:
  type: ClusterIP
  selector:
    app: seyoawe-engine
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: dispatcher
      port: 8081
      targetPort: 8081
      protocol: TCP
